### ISSUE TITLE
questions about regression test

### ISSUE THREAD

**Issue by aisfyhhh** [aignacio/ravenoc#19]
I am a beginner in NoC and I am more familiar with HDL languages. I downloaded the run_dir folder according to the Quickstart regression using Git Bash. I don't quite understand the purpose of the files in the folder. Are the files in the run_dir folder the results of the testbench execution? What do the suffixes coffee and vanilla represent? If I only want to learn the complete architecture of NoC, can I only focus on the src and tb folders?
<img width="312" alt="fc2dfb3bc31d2cf409eb7901ade52bf" src="https://github.com/user-attachments/assets/12652ebd-13f9-470e-bb8b-85c95dc82552">

**Comment by aignacio** [comment]
Hey @aisfyhhh,
pls check inline.

> I am a beginner in NoC and I am more familiar with HDL languages. I downloaded the run_dir folder according to the Quickstart regression using Git Bash. I don't quite understand the purpose of the files in the folder. Are the files in the run_dir folder the results of the testbench execution? 

These files are generated from the execution of all tests, within that you have the generated verilator executable model, the waveforms and some log files. If the test execution succeeded, you should have waveforms for all tests.

> What do the suffixes coffee and vanilla represent? If I only want to learn the complete architecture of NoC, can I only focus on the src and tb folders?

The suffixes are some pre-defined configurations for the NoC, more info [here](https://github.com/aignacio/ravenoc/tree/master/tb). If you want to learn, I suggest checking the simple config (vanilla) waveforms and the RTL in [`src`](https://github.com/aignacio/ravenoc/tree/master/src).

**Comment by aisfyhhh** [comment]
Hello, @aignacio, I have learned a lot from this project. But now I have two questions about the testbench. 1. After running the regression tests for the NoC, I got FF....F and the container cannot exit. Does the "F" mean the test failed, and the "." means the test passed? I noticed that some folders don't have dump.fst files in them. I haven't made any changes to the project's code, and I have provided the container with sufficient resources. 

2. After reading the readme file in the tb folder, can I assume that all the relevant waveforms for the latest_sim-starting log files are reflected in the same dump.fst file? My English is not very proficient, so I may not fully understand the meaning of the readme file. I uploaded the relevant pictures. Thanks for your help.
<img width="957" alt="12253edd595430def4279fbe2a5f6a5" src="https://github.com/user-attachments/assets/1db6236d-0164-4fcd-a4a0-ded6e8ed299f">
<img width="689" alt="ac85ff5bed305b3882ca3e7b250d154" src="https://github.com/user-attachments/assets/df773428-0976-4183-acc6-5aa97c0f438d">

**Comment by aignacio** [comment]
Hey @aisfyhhh, I'm happy that you found this project useful!

1. About the first question, you're correct . = test pass and F = test fail. It has been a while since I run the regression but I tried with my computer and I saw some Fs too, when I tried in a machine with more resources I had them all passing as you can check below. It took around 40 minutes to complete but I realized that when I was running in my small setup, docker was killing some jobs, not sure why honestly. I have attached the .fst in case you want to debug.

<img width="781" alt="image" src="https://github.com/user-attachments/assets/2646c823-9596-443b-a827-ba6215438315">

https://file.io/OCK7tKn1x2bb

2. Yes, you can assume that, all logs should match the waveforms too, if there's a particular test you are not sure about what is doing or you are interested on changing it, try to run with the command below.
```bash
❯ docker run --rm --name ravenoc_run -v $(pwd):/ravenoc -w /ravenoc aignacio/ravenoc tox -- -rP -k test_ravenoc_basic.py
```
