### ISSUE TITLE
router top file：Confused about ns_con

### ISSUE THREAD

**Issue by Elena32061** [aignacio/ravenoc#9]
Sir, I'm confused by this "con", I guess it's an abbreviation for connection, but what about the ns in front of it? Why only ns, sn, not nw, ne? Can you answer my doubts when you have time? Thank you very much!

router_if ns_con [(NoCCfgSzRows+1)*NoCCfgSzCols] ();
   router_if sn_con [(NoCCfgSzRows+1)*NoCCfgSzCols] ();
   router_if we_con [NoCCfgSzRows*(NoCCfgSzCols+1)] ();
   router_if ew_con [NoCCfgSzRows*(NoCCfgSzCols+1)] ();

**Comment by aignacio** [comment]
Hi @Elena32061 
please add a link to the particular line in the file you're talking about. The abbreviation of con means connection and the reason why I have only ns/sn/we/ew it's because you have only wires in XY direction between routers, take a look at this image down below.
![image](https://raw.githubusercontent.com/aignacio/ravenoc/5685fc3605888917dab9b384d753c27582cd0345/docs/img/router_connections.svg)

**Comment by Elena32061** [comment]
I'm sorry, sir. I didn't think hard about this question。 it's so stupid. Thank you for your patience
